### ISSUE TITLE
Switcher not working

### ISSUE THREAD

**Issue by fhuettner** [QubitProducts/dashing-contrib#12]
Hi,

how can i only use the Switcher widget?

Example:
```html
	<li data-switcher-interval="3000" data-row="1" data-col="1" data-sizex="1" data-sizey="1">
	  <div data-id="weather-680564" data-view="Weather" data-location="Nürnberg"></div>
	  <div data-id="weather-676757" data-view="Weather" data-location="München"></div>
	</li>
```
The switcher.coffee file is in widgets/switcher/

Any thing else?

**Comment by activars** [comment]
Hi, did you include dashing-contrib gem into your dashing project?

**Comment by frounzn** [comment]
I´ve have the same problem. I followed the installation instructions from https://github.com/QubitProducts/dashing-contrib. 
Should I post the modified config files, so you can check if there is an error?

**Comment by activars** [comment]
yes please, did you install the latest version?

**Comment by frounzn** [comment]
I did a fresh install. I´m on ubuntu with ruby 1.9.3.
```
gem install dashing
dashing new dashx
cd dashx
bundle
dashing start
dashing stop # crtl-c
```

*# head Gemfile*
```
source 'https://rubygems.org'

gem 'dashing'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
gem 'dashing-contrib', '~> 0.1.7'
```

*# head config.ru*
```
$: << File.expand_path('./lib', File.dirname(__FILE__))
require 'dashing-contrib'
require 'dashing'
DashingContrib.configure
configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'
```
*# head assets/javascripts/application.coffee*
```
# dashing.js is located in the dashing framework
# It includes jquery & batman for you.
#= require dashing.js

#= require_directory .
#= require_tree ../../widgets
#=require dashing-contrib/assets/widgets

console.log("Yeah! The dashboard has started!")
```
*# head assets/stylesheets/application.scss*
```
/*
  //=require_directory .
  //=require_tree ../../widgets
  //=require dashing-contrib/assets/widgets
*/
```
then i did bundle & dashing start

**Comment by fjakop** [comment]
same problem here, identical config as above.
The configured widgets inside the switcher are displayed horizontally next to each other, the rest of the layout looks broken.
![switcher-broken](https://cloud.githubusercontent.com/assets/1125261/6389073/adb1aa66-bda0-11e4-93af-ef0dc16543eb.png)
![without-switcher](https://cloud.githubusercontent.com/assets/1125261/6389074/b2aa890c-bda0-11e4-809d-9b51dc2125f4.png)

**Comment by activars** [comment]
Could you try to upgrade ruby? I had issues with 1.9.3 that doesn't pass my unit test, I believe that some libraries is not supporting ruby 1.9.3

The list of tested Ruby versions: 
https://github.com/QubitProducts/dashing-contrib/blob/master/.travis.yml

**Comment by fjakop** [comment]
Same problem with ruby 2.0.0
```
Puma starting in single mode...
* Version 2.11.1 (ruby 2.0.0-p598), codename: Intrepid Squirrel
* Min threads: 0, max threads: 16
* Environment: development
append to sprockets path: /usr/local/lib/ruby/gems/2.0.0/gems/dashing-contrib-0.1.8/lib
#<Sprockets::Environment:0xa1afce8>
* Listening on tcp://0.0.0.0:9292
```

**Comment by activars** [comment]
Could you try lock down dashing-contrib version to 0.1.6? just incase that the latest release could break it.

**Comment by fjakop** [comment]
How does this work? I put this in my Gemfile
gem 'dashing-contrib', '0.1.6'

but I still get
append to sprockets path: /usr/local/lib/ruby/gems/2.0.0/gems/dashing-contrib-0.1.8/lib

**Comment by activars** [comment]
em, that's strange. Did you restart the dashing server?

**Comment by fjakop** [comment]
so when I start via
`dashing start`
I get 
```
append to sprockets path: /usr/local/lib/ruby/gems/2.0.0/gems/dashing-contrib-0.1.6/lib
#<Sprockets::Environment:0x9a8691c>
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
```

but the problem with the native dashing server is that it does not work with chrome browser, so I use puma for starting.
Gemfile
```
source 'https://rubygems.org'
gem 'dashing'
gem 'dashing-contrib', '0.1.6'
gem 'puma'
gem 'teamcity-ruby-client'
```

This works well with all browsers.

I figured out that I had to remove 0.1.8 by
`bundle clean --force`
Now it takes 0.1.6 but no change, still shows all widgets and kills the layout.

**Comment by fjakop** [comment]
Can I do something else to support you in fixing this issue?

**Comment by activars** [comment]
If it's not sensitive, it would be create to get your project in zip file so I can reproduce the issue locally.

**Comment by fjakop** [comment]
There it is https://www.dropbox.com/s/h4lm2zdbzwzalgj/infomonitor.tar.gz?dl=0
The TeamCity job will not work as long you do not have a TeamCity-Server and configure it, but the widget is not included anyway.

**Comment by activars** [comment]
Thanks, I will take a look the issue tonight for you.


On 3 March 2015 at 14:30, fjakop <notifications@github.com> wrote:

> There it is
> https://www.dropbox.com/s/h4lm2zdbzwzalgj/infomonitor.tar.gz?dl=0
> The TeamCity job will not work as long you do not have a TeamCity-Server
> and configure it, but the widget is not included anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QubitProducts/dashing-contrib/issues/12#issuecomment-76955076>
> .
>



-- 
This email may be confidential or privileged. If you received this
communication
by mistake, please don't forward it to anyone else, please erase all copies
and attachments, and please let me know that it has gone the wrong person.
Thanks.

**Comment by frounzn** [comment]
any news on this? 
@activars do you use node.js ? Which version?

**Comment by rlester** [comment]
I am also, seeing the issue displayed above. 

Using Ruby version: ruby-2.1.4
Tried dashing-contrib 1.6  and 1.7.

**Comment by ianmoone** [comment]
up

**Comment by tracstarr** [comment]
I am also having the same issues and tried as per above as well.

**Comment by fleeting** [comment]
Has anybody had any luck on this? It looks like the javascript is throwing an error of `Uncaught ReferenceError: elements is not defined` on `this.$elements = $(elements);`. Full function is below.

```
function WidgetSwitcher(elements1) {
      this.elements = elements1;
      this.$elements = $(elements);
}
```

inside `WidgetSwitcher = (function() { }`.

**Comment by activars** [comment]
I accept PR if anyone have a solution to fix this issue.

**Comment by SergioGomez321** [comment]
Hey, what was the solution for the  @fjakop  problem?  
I have the same issue :(
