### ISSUE TITLE
How Do I Run A Custom Job?

### ISSUE THREAD

**Issue by rlester** [QubitProducts/dashing-contrib#14]
I have implemented a custom job but I can't seem to figure out how to run it.

I am sure I am doing something wrong but here are my current assumptions:

- Since the runnable job replaces "'SCHEDULE.every' " call, I assume that the self.metrics function is now used for making the request for the metric as well as returning it. 

- That there is some place somewhere that I need to call "MyCustomJob.run(event: 'custom-job-event', every: '20s')" but I am not sure where, and I wasn't able to find an example of how to run it. The only examples I was able to find used "'SCHEDULE.every' "

If someone could point me the in the right direction it would be greatly appreciated.

**Comment by activars** [comment]
You should put the your custom jobs code in the jobs directory (as usual).

**Comment by rlester** [comment]
Ah, I think I understand it now. If I wanted to create my own job templates I should be forking this repo. Then including my fork as part of my dashing project. Then define the job templates in the fork and the actual running of the jobs in the dashing project? Similar to how if I wanted to us the pingdom job. The job has already been defined in dashing-contrib and in my project I would just call run with the configurations I need. Is this correct?

**Comment by activars** [comment]
Yup, that's correct :)


On 11 Mar 2015, at 20:58, Rob Lester <notifications@github.com> wrote:

Ah, I think I understand it now. If I wanted to create my own job templates
I should be forking this repo. Then including my fork as part of my dashing
project. Then define the job templates in the fork and the actual running
of the jobs in the dashing project? Similar to how if I wanted to us the
pingdom job. The job has already been defined in dashing-contrib and in my
project I would just call run with the configurations I need. Is this
correct?

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/dashing-contrib/issues/14#issuecomment-78369957>
.

**Comment by rlester** [comment]
Awesome, thank you for your help.
