### ISSUE TITLE
Quick Question : Definition of Pingdom Uptime Month

### ISSUE THREAD

**Issue by MWilkinson** [QubitProducts/dashing-contrib#20]
Hi, I've just started looking at this and noticed that line 46 of
 `dashing-contrib/lib/dashing-contrib/jobs/pingdom_uptime.rb` defined 
`t1_month = t24_hour * 4` 
shouldn't this really be 
`t1_month = t24_hour * 7 * 4` ?

**Comment by activars** [comment]
I think you are correct. Do you mind create an PR? I'm happy to merge it asap.
