### ISSUE TITLE
thor version conflict

### ISSUE THREAD

**Issue by maticrivo** [QubitProducts/dashing-contrib#35]
Hey, I'm using the forked version of [dashing](https://github.com/Dashing-io/dashing) and when trying to install i get a conflict in `thor` version:
```sh
$ bundle install
Fetching https://github.com/Dashing-io/dashing.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    dashing-contrib (~> 0.2.2) was resolved to 0.2.2, which depends on
      dashing (~> 1.3) was resolved to 1.3.6, which depends on
        thor (~> 0.19)

    dashing-contrib (~> 0.2.2) was resolved to 0.2.2, which depends on
      thor (~> 0.18.1)
```
any idea how i can fix this?

**Comment by activars** [comment]
@maticrivo in your forked version, you can update `thor` version to `~> 0.19` in the gemspec.

This is the line:
https://github.com/QubitProducts/dashing-contrib/blob/master/dashing-contrib.gemspec#L22

**Comment by activars** [comment]
@maticrivo after looking at a couple of forks, it seems to be an common issue. 
Happy to accept your PR, I will merge and release a new version asap.

Thanks

**Comment by maticrivo** [comment]
@activars thanks, i opened a PR #36
