### ISSUE TITLE
Memory Leak due to outdated sideqick version

### ISSUE THREAD

**Issue by fhur** [QubitProducts/dashing-contrib#37]
As evidenced by this PR: https://github.com/mperham/sidekiq/pull/2598, dashing-contrib is using an outdated sidekiq version which has a memory leak. According to https://github.com/ASoftCo/leaky-gems this issue affects sidekiq < 3.5.1
The fix should be as simple as updating to the latest sidekiq. The latest version is `4.2.3` (https://github.com/mperham/sidekiq/tags)

**Comment by activars** [comment]
The latest version that doesn't break existing test or api is 3.5.4 at the moment.
The changes are applied in PR #38 & test passed.

If you are happy with it, please give a thumbsup or late halloween pumpkin :D, then I will merge and release it asap. 

I'm also happy to accept PR if you want to add support for Sidekiq 4.x - there's a Sidekiq API compatibility issues with 4.x.

**Comment by fhur** [comment]
Yeah that should be fine. I can't promise adding support for Sidekiq 4.x but I will take a look into it.
